name: alquran_cloud
description: un-official dart client wrapper for the quran.cloud api consume the holy book of quran
version: 0.0.1
repository: https://github.com/maxzod/alquran_cloud
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  equatable: ^2.0.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  lint: ^1.5.3
  test: ^1.14.4
